### ISSUE TITLE
usersクエリを走らせたときのエラー

### ISSUE THREAD

**Issue by KoichiKiyokawa** [KoichiKiyokawa/nest-graphql-prisma#1]
```
{
  "errors": [
    {
      "message": "graphql_fields_1.default is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: graphql_fields_1.default is not a function",
            "    at UserCrudResolver.users (/Users/koichi/prg/sandbox/nest-graphql-prisma/dist/prisma/generated/type-graphql/resolvers/crud/User/UserCrudResolver.js:45:78)",
            "    at /Users/koichi/prg/sandbox/nest-graphql-prisma/node_modules/type-graphql/dist/resolvers/create.js:31:98",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by KoichiKiyokawa** [comment]
graphql_fieldsライブラリがなんかバグってる？
